name = "based"
version = "2.0.0"
description = "A common interface for database backends"
gleam = "~> 1.0"

licences = ["Apache-2.0"]
repository = { type = "github", user = "stndrs", repo = "based" }

[dependencies]
gleam_stdlib = ">= 0.38.0 and < 2.0.0"
gleam_otp = ">= 0.10.0 and < 1.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
