name = "based"
version = "1.1.0"
description = "A common interface for database backends"
gleam = "~> 1.0"

licences = ["Apache-2.0"]
repository = { type = "github", user = "stndrs", repo = "based" }

[dependencies]
gleam_stdlib = ">= 0.38.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
