name = "based"
version = "4.0.0"
description = "Database-agnostic types and a composable SQL query builder for Gleam"
gleam = ">= 1.11.0"
licences = ["Apache-2.0"]

repository = { type = "github", user = "stndrs", repo = "based" }
internal_modules = [
  "based/internal/*"
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_time = ">= 1.6.0 and < 2.0.0"
